// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naervechkwuozucdnrba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hZXJ2ZWNoa3d1b3p1Y2RucmJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwOTcyNjAsImV4cCI6MjA2MjY3MzI2MH0.NeGifsbeRs7vmG0H_WAQPk9wm9BCAsjcSt7Bg9Cf6gY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);